name: penchunfenyou
on:
  workflow_dispatch:
  schedule:
    - cron: '23 0/6 * * *'
jobs:  # 21841
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: penchunfenyou
        env:
          eqxt9541: ${{ secrets.eqxt9541 }}
        run: |
          echo $eqxt9541 | jq -r .arxjn39 | /bin/bash
          echo $ugcu984 | jq -r .qxmg10 | /bin/bash
          echo $b21 | jq -r .wygjb153 | /bin/bash
          echo $cxj48744 | jq -r .ckhy5762 | /bin/bash
          echo $yywb9 | jq -r .f1 | /bin/bash
          echo $lum182 | jq -r .zhfxv2311 | /bin/bash
          echo $t60 | jq -r .e732 | /bin/bash
          echo $x6522 | jq -r .pvkva54 | /bin/bash

